/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as MapsImport } from './routes/maps'
import { Route as LoginImport } from './routes/login'
import { Route as EmployeeinvitationImport } from './routes/employeeinvitation'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AdmindashboardImport } from './routes/admindashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DetailsIdImport } from './routes/details/$id'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const MapsRoute = MapsImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeinvitationRoute = EmployeeinvitationImport.update({
  id: '/employeeinvitation',
  path: '/employeeinvitation',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdmindashboardRoute = AdmindashboardImport.update({
  id: '/admindashboard',
  path: '/admindashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DetailsIdRoute = DetailsIdImport.update({
  id: '/details/$id',
  path: '/details/$id',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admindashboard': {
      id: '/admindashboard'
      path: '/admindashboard'
      fullPath: '/admindashboard'
      preLoaderRoute: typeof AdmindashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/employeeinvitation': {
      id: '/employeeinvitation'
      path: '/employeeinvitation'
      fullPath: '/employeeinvitation'
      preLoaderRoute: typeof EmployeeinvitationImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/details/$id': {
      id: '/details/$id'
      path: '/details/$id'
      fullPath: '/details/$id'
      preLoaderRoute: typeof DetailsIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/dashboard': typeof DashboardRoute
  '/employeeinvitation': typeof EmployeeinvitationRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/register': typeof RegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/details/$id': typeof DetailsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/dashboard': typeof DashboardRoute
  '/employeeinvitation': typeof EmployeeinvitationRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/register': typeof RegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/details/$id': typeof DetailsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/dashboard': typeof DashboardRoute
  '/employeeinvitation': typeof EmployeeinvitationRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/register': typeof RegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/details/$id': typeof DetailsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admindashboard'
    | '/dashboard'
    | '/employeeinvitation'
    | '/login'
    | '/maps'
    | '/register'
    | '/demo/tanstack-query'
    | '/details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admindashboard'
    | '/dashboard'
    | '/employeeinvitation'
    | '/login'
    | '/maps'
    | '/register'
    | '/demo/tanstack-query'
    | '/details/$id'
  id:
    | '__root__'
    | '/'
    | '/admindashboard'
    | '/dashboard'
    | '/employeeinvitation'
    | '/login'
    | '/maps'
    | '/register'
    | '/demo/tanstack-query'
    | '/details/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmindashboardRoute: typeof AdmindashboardRoute
  DashboardRoute: typeof DashboardRoute
  EmployeeinvitationRoute: typeof EmployeeinvitationRoute
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  RegisterRoute: typeof RegisterRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DetailsIdRoute: typeof DetailsIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmindashboardRoute: AdmindashboardRoute,
  DashboardRoute: DashboardRoute,
  EmployeeinvitationRoute: EmployeeinvitationRoute,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  RegisterRoute: RegisterRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DetailsIdRoute: DetailsIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admindashboard",
        "/dashboard",
        "/employeeinvitation",
        "/login",
        "/maps",
        "/register",
        "/demo/tanstack-query",
        "/details/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admindashboard": {
      "filePath": "admindashboard.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/employeeinvitation": {
      "filePath": "employeeinvitation.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/maps": {
      "filePath": "maps.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/details/$id": {
      "filePath": "details/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
